# fly.toml app configuration file generated for money-mindset on 2023-07-23T18:51:34+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "money-mindset"
primary_region = "nrt"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
